let nodes = new vis.DataSet([
    {
        id: 1,
        value: 1,
        group: "Carrer",
        label: "Carrer",
        x: 0,
        y: 0,
        fixed: {
            x: true,
            y: true,
        },
    },
    {
        id: 2,
        value: 1,
        group: "SelfGrowth",
        label: "Self-Growth",
        x: -100,
        y: -125,
    },
    {
        id: 3,
        value: 1,
        group: "DrivesResults",
        label: "Drives Results",
        x: 0,
        y: -150,
    },
    {
        id: 4,
        value: 1,
        group: "StrategicMindset",
        label: "Strategic Mindset",
        x: 100,
        y: -125,
    },
    { id: 5, value: 1, group: "Alignment", label: "Alignment", x: 140, y: 75 },
    { id: 6, value: 1, group: "Ambiguity", label: "Ambiguity", x: 150, y: -25 },
    {
        id: 7,
        value: 1,
        group: "Interconnectivity",
        label: "Interconnectivity",
        x: 60,
        y: 150,
    },
    {
        id: 8,
        value: 1,
        group: "Communication",
        label: "Communication",
        x: -60,
        y: 150,
    },
    {
        id: 9,
        value: 1,
        group: "BalancesStakeholders",
        label: "Balances Stakeholders",
        x: -140,
        y: 75,
    },
    {
        id: 10,
        value: 1,
        group: "Adaptability",
        label: "Adaptability",
        x: -150,
        y: -25,
    },
    {
        id: 11,
        value: 1,
        group: "BalancesStakeholders",
        label: "Lend Your Ear",
        x: -200,
        y: 150,
    },
    {
        id: 12,
        value: 1,
        group: "BalancesStakeholders",
        label: "Cultural Awareness",
        x: -300,
        y: 250,
    },
    {
        id: 13,
        value: 1,
        group: "BalancesStakeholders",
        label: "People Skills",
        x: -300,
        y: 150,
    },
    {
        id: 14,
        value: 1,
        group: "BalancesStakeholders",
        label: "Cultural Savvy",
        x: -325,
        y: 475,
    },
    {
        id: 15,
        value: 1,
        group: "BalancesStakeholders",
        label: "People Management",
        x: -400,
        y: 600,
    },
    {
        id: 16,
        value: 1,
        group: "Communication",
        label: "Critical Listening",
        x: -150,
        y: 250,
    },
    {
        id: 17,
        value: 1,
        group: "Communication",
        label: "Concision",
        x: -50,
        y: 250,
    },
    {
        id: 18,
        value: 1,
        group: "Communication",
        label: "Experienced Writer",
        x: -50,
        y: 350,
    },
    {
        id: 19,
        value: 1,
        group: "Communication",
        label: "Content Creator",
        x: -50,
        y: 475,
    },
    {
        id: 20,
        value: 1,
        group: "Communication",
        label: "Experienced Speaker",
        x: -200,
        y: 350,
    },
    {
        id: 21,
        value: 1,
        group: "Communication",
        label: "Critical Listening II",
        x: -200,
        y: 475,
    },
    {
        id: 22,
        value: 1,
        group: "Communication",
        label: "Forum Moderator",
        x: -250,
        y: 575,
    },
    {
        id: 23,
        value: 1,
        group: "Communication",
        label: "Expert Speaker",
        x: -150,
        y: 575,
    },
    {
        id: 24,
        value: 1,
        group: "Communication",
        label: "Forum Moderator II",
        x: -300,
        y: 675,
    },
    {
        id: 25,
        value: 1,
        group: "Communication",
        label: "Curiousity",
        x: -200,
        y: 675,
    },
    {
        id: 26,
        value: 1,
        group: "Communication",
        label: "Veteran Oratory",
        x: -175,
        y: 750,
    },
]);

let edges = new vis.DataSet([
    { from: 1, to: 2, arrows: "to" },
    { from: 1, to: 3, arrows: "to" },
    { from: 1, to: 4, arrows: "to" },
    { from: 1, to: 5, arrows: "to" },
    { from: 1, to: 6, arrows: "to" },
    { from: 1, to: 7, arrows: "to" },
    { from: 1, to: 8, arrows: "to" },
    { from: 1, to: 9, arrows: "to" },
    { from: 1, to: 10, arrows: "to" },
    { from: 9, to: 11, arrows: "to" },
    { from: 11, to: 12, arrows: "to" },
    { from: 12, to: 14, arrows: "to" },
    { from: 9, to: 13, arrows: "to" },
    { from: 14, to: 15, arrows: "to" },
    { from: 11, to: 16, arrows: "to" },
    { from: 8, to: 16, arrows: "to" },
    { from: 8, to: 17, arrows: "to" },
    { from: 17, to: 18, arrows: "to" },
    { from: 18, to: 19, arrows: "to" },
    { from: 16, to: 19, arrows: "to" },
    { from: 16, to: 20, arrows: "to" },
    { from: 20, to: 21, arrows: "to" },
    { from: 21, to: 22, arrows: "to" },
    { from: 21, to: 23, arrows: "to" },
    { from: 22, to: 24, arrows: "to" },
    { from: 22, to: 25, arrows: "to" },
    { from: 23, to: 26, arrows: "to" },
]);
