let nodes = new vis.DataSet([
    {
        id: 1,
        value: 1,
        group: "Carrer",
        label: "What skills are important in\nupper management preparation?",
        image: "images/placeholder.png",
        value: 40,
        disabled: true,
        x: 0,
        y: 0,
        fixed: {
            x: true,
            y: true,
        },
    },
    {
        id: 2,
        value: 1,
        group: "SelfGrowth",
        label: "Self-Growth",
        image: "images/placeholder.png",
        description:
            "Actively seek ways to grow and be challenged using development channels.",
        x: -100,
        y: -125,
    },
    {
        id: 3,
        value: 1,
        group: "OutcomesDriven",
        label: "Outcomes Driven",
        image: "images/placeholder.png",
        description: "Achieve results, despite the circumstances.",
        x: 0,
        y: -150,
    },
    {
        id: 4,
        value: 1,
        group: "StrategicMindset",
        label: "Strategic Mindset",
        image: "images/placeholder.png",
        description:
            "Decides the best course of action for future trajectories.",
        x: 100,
        y: -125,
    },
    {
        id: 5,
        value: 1,
        group: "Alignment",
        label: "Alignment",
        image: "images/placeholder.png",
        description:
            "Plans and prioritizes work to meet commitments aligned with organizational goals.",
        x: 140,
        y: 75,
    },
    {
        id: 6,
        value: 1,
        group: "Ambiguity",
        label: "Ambiguity",
        image: "images/placeholder.png",
        description:
            "Operates well, even when contexts and objectives are not certain or clear cut.",
        x: 150,
        y: -25,
    },
    {
        id: 7,
        value: 1,
        group: "Interconnectivity",
        label: "Interconnectivity",
        image: "images/placeholder.png",
        description: "Converse and relate comfortably with diverse groups.",
        x: 60,
        y: 150,
    },
    {
        id: 8,
        value: 1,
        group: "Communication",
        label: "Communication",
        image: "images/placeholder.png",
        description:
            "Develop and express thoughts and feelings to an audience.",
        x: -60,
        y: 150,
    },
    {
        id: 9,
        value: 1,
        group: "BalancesStakeholders",
        label: "Balances Stakeholders",
        image: "images/placeholder.png",
        description:
            "Address needs of multiple groups associated with the organization.",
        x: -140,
        y: 75,
    },
    {
        id: 10,
        value: 1,
        group: "Adaptability",
        label: "Adaptability",
        image: "images/placeholder.png",
        description:
            "Shifting behaviors to fit organizational context in real time.",
        x: -150,
        y: -25,
    },
    {
        id: 11,
        value: 1,
        group: "BalancesStakeholders",
        label: "Lend Your Ear",
        image: "images/placeholder.png",
        description:
            "Listens to others to gain an understanding of various stakeholder priorities.",
        x: -200,
        y: 175,
    },
    {
        id: 12,
        value: 1,
        group: "BalancesStakeholders",
        label: "Cultural Awareness",
        image: "images/placeholder.png",
        description:
            "Understand and respect different cultures and values of different groups.",
        x: -300,
        y: 325,
    },
    {
        id: 13,
        value: 1,
        group: "BalancesStakeholders",
        label: "People Skills",
        image: "images/placeholder.png",
        description: "Engages effectively with multiple stakeholders.",
        x: -300,
        y: 175,
    },
    {
        id: 14,
        value: 1,
        group: "BalancesStakeholders",
        label: "Cultural Savvy",
        image: "images/placeholder.png",
        description:
            "Navigate multiple cultural spaces with respect and professionalism for each of their norms and values.",
        x: -350,
        y: 550,
    },
    {
        id: 15,
        value: 1,
        group: "BalancesStakeholders",
        label: "Workplace Culture",
        image: "images/placeholder.png",
        description:
            "Create, embody, and enforce organizational culture in which people follow the highest ethics and deepest cultural sensitivity.",
        x: -475,
        y: 650,
    },
    {
        id: 16,
        value: 1,
        group: "Communication",
        label: "Been Present",
        image: "images/placeholder.png",
        description:
            "Pay attention to others' insights, advice, or instructions to grasp main concepts and pieces.",
        x: -150,
        y: 250,
    },
    {
        id: 17,
        value: 1,
        group: "Communication",
        label: "Concision",
        image: "images/placeholder.png",
        description:
            "Promptly shares relevant info with right amount of detail.",
        x: -50,
        y: 275,
    },
    {
        id: 18,
        value: 1,
        group: "Communication",
        label: "Experienced Writer",
        image: "images/placeholder.png",
        description: "Gives appropriate context and details when writing.",
        x: -50,
        y: 400,
    },
    {
        id: 19,
        value: 1,
        group: "Communication",
        label: "Content Creator",
        image: "images/placeholder.png",
        description:
            "Produces rich, professional documents and reports that widely shared internally and externally of the organization.",
        x: -50,
        y: 550,
    },
    {
        id: 20,
        value: 1,
        group: "Communication",
        label: "Experienced Speaker",
        image: "images/placeholder.png",
        description: "Gives appropriate context and details when speaking.",
        x: -200,
        y: 350,
    },
    {
        id: 21,
        value: 1,
        group: "Communication",
        label: "Critical Listening",
        image: "images/placeholder.png",
        description:
            "Listens carefully and probes beneath the surface to gain richer insight on others' views.",
        x: -200,
        y: 475,
    },
    {
        id: 22,
        value: 1,
        group: "Communication",
        label: "Forum Moderator",
        image: "images/placeholder.png",
        description:
            "Creates forums for people to express themselves openly and regularly.",
        x: -250,
        y: 575,
    },
    {
        id: 23,
        value: 1,
        group: "Communication",
        label: "Expert Speaker",
        image: "images/placeholder.png",
        description:
            "Delivers messages effectively to all levels of the organization, tailoring communication content and style to the needs of others.",
        x: -150,
        y: 575,
    },
    {
        id: 24,
        value: 1,
        group: "Communication",
        label: "Advanced Forum Moderator",
        image: "images/placeholder.png",
        description:
            "Pays attention to others' input and perspectives, asks questions, and summarizes to confirm understanding.",
        x: -300,
        y: 675,
    },
    {
        id: 25,
        value: 1,
        group: "Communication",
        label: "Veteran Oratory",
        image: "images/placeholder.png",
        description:
            "Has a strong, compelling impact on people at all levels, building interest and commitment and creating culture of ongoing constructive dialogue.",
        x: -150,
        y: 675,
    },
    {
        id: 26,
        value: 1,
        group: "BalancesStakeholders",
        label: "People Research",
        image: "images/placeholder.png",
        description: "Learn about various stakeholders and gain insight.",
        x: -300,
        y: 50,
    },
    {
        id: 27,
        value: 1,
        group: "BalancesStakeholders",
        label: "Preemptive Strike",
        image: "images/placeholder.png",
        description:
            "Takes initiative to respond to stakeholder concerns and issues.",
        x: -400,
        y: 175,
    },
    {
        id: 28,
        value: 1,
        group: "BalancesStakeholders",
        label: "Insider Knowledge",
        image: "images/placeholder.png",
        description:
            "Probes deeper to gain richer details and backgrounds about stakeholders.",
        x: -400,
        y: 300,
    },
    {
        id: 29,
        value: 1,
        group: "BalancesStakeholders",
        label: "Integrity",
        image: "images/placeholder.png",
        description:
            "Ensures people understand and adhere to ethical standards when working with stakeholders.",
        x: -400,
        y: 400,
    },
    {
        id: 30,
        value: 1,
        group: "BalancesStakeholders",
        label: "Advanced Integrity",
        image: "images/placeholder.png",
        description: "Promotes and environment of high ethical standards.",
        x: -475,
        y: 550,
    },
    {
        id: 31,
        value: 1,
        group: "BalancesStakeholders",
        label: "Crowd Working",
        image: "images/placeholder.png",
        description:
            "Respond to stakeholders with well-balanced, win-win solutions.",
        x: -500,
        y: 400,
    },
    {
        id: 32,
        value: 1,
        group: "BalancesStakeholders",
        label: "Crowd Management",
        image: "images/placeholder.png",
        description:
            "Maximize outcomes for all stakeholders and identify all relevant issues.",
        x: -600,
        y: 550,
    },
    {
        id: 33,
        value: 1,
        group: "Interconnectivity",
        label: "Openness",
        image: "images/placeholder.png",
        description:
            "Listens and responds non-defensively when given advice, instruction, or feedback.",
        x: 60,
        y: 250,
    },
    {
        id: 34,
        value: 1,
        group: "Interconnectivity",
        label: "Countenance",
        image: "images/placeholder.png",
        description:
            "Maintains an open, accepting demeanor when interacting with others.",
        x: 150,
        y: 250,
    },
    {
        id: 35,
        value: 1,
        group: "Interconnectivity",
        label: "Tact",
        image: "images/placeholder.png",
        description:
            "Shows sensible reactions and sensitivity in difficult interpersonal situations.",
        x: 50,
        y: 375,
    },
    {
        id: 36,
        value: 1,
        group: "Interconnectivity",
        label: "Social Awareness I",
        image: "images/placeholder.png",
        description:
            "Grasp others' more obvious social cues and responds appropriately.",
        x: 150,
        y: 350,
    },
    {
        id: 37,
        value: 1,
        group: "Interconnectivity",
        label: "Tactition",
        image: "images/placeholder.png",
        description:
            "Helps to diffuse difficult interpersonal situations by showing high levels of tact, sensitivity, and consideration.",
        x: 75,
        y: 500,
    },
    {
        id: 38,
        value: 1,
        group: "Interconnectivity",
        label: "Social Awareness II",
        image: "images/placeholder.png",
        description:
            "Grasp others' subtle social cues and nimbly responds to others' needs and concerns.",
        x: 175,
        y: 475,
    },
    {
        id: 39,
        value: 1,
        group: "Interconnectivity",
        label: "Unity",
        image: "images/placeholder.png",
        description: "Works to build greater group harmony.",
        x: 125,
        y: 600,
    },
    {
        id: 40,
        value: 1,
        group: "Interconnectivity",
        label: "People Management",
        image: "images/placeholder.png",
        description:
            "Understands the nuances of interpersonal group dynamics and leverages this knowledge to achieve results.",
        x: 175,
        y: 675,
    },
    {
        id: 41,
        value: 1,
        group: "Interconnectivity",
        label: "Tutelage",
        image: "images/placeholder.png",
        description: "Coach members on interpersonal skills..",
        x: 250,
        y: 575,
    },
    {
        id: 42,
        value: 1,
        group: "Interconnectivity",
        label: "People Liaison",
        image: "images/placeholder.png",
        description:
            "Picks up on team interpersonal dynamics and finds ways to work effectively and resolve interpersonal conflict, internal and external to the organization.",
        x: 325,
        y: 675,
    },
]);

let edges = new vis.DataSet([
    { from: 1, to: 2, arrows: "to", hidden: true },
    { from: 1, to: 3, arrows: "to", hidden: true },
    { from: 1, to: 4, arrows: "to", hidden: true },
    { from: 1, to: 5, arrows: "to", hidden: true },
    { from: 1, to: 6, arrows: "to", hidden: true },
    // Interconnectivity
    { from: 1, to: 7, arrows: "to", hidden: true },
    { from: 7, to: 33, arrows: "to" },
    { from: 33, to: 35, arrows: "to" },
    { from: 35, to: 37, arrows: "to" },
    { from: 33, to: 36, arrows: "to" },
    { from: 36, to: 38, arrows: "to" },
    { from: 38, to: 41, arrows: "to" },
    { from: 41, to: 42, arrows: "to" },
    { from: 37, to: 39, arrows: "to" },
    { from: 38, to: 39, arrows: "to" },
    { from: 39, to: 40, arrows: "to" },
    { from: 7, to: 34, arrows: "to" },
    // Communication
    { from: 1, to: 8, arrows: "to", hidden: true },
    { from: 8, to: 16, arrows: "to" },
    { from: 16, to: 20, arrows: "to" },
    { from: 20, to: 21, arrows: "to" },
    { from: 8, to: 17, arrows: "to" },
    { from: 17, to: 18, arrows: "to" },
    { from: 18, to: 19, arrows: "to" },
    { from: 21, to: 19, arrows: "to" },
    { from: 21, to: 22, arrows: "to" },
    { from: 21, to: 23, arrows: "to" },
    { from: 22, to: 24, arrows: "to" },
    { from: 23, to: 25, arrows: "to" },
    // Balances Stakeholders
    { from: 1, to: 9, arrows: "to", hidden: true },
    { from: 9, to: 11, arrows: "to" },
    { from: 11, to: 12, arrows: "to" },
    { from: 9, to: 13, arrows: "to" },
    { from: 13, to: 12, arrows: "to" },
    { from: 12, to: 14, arrows: "to" },
    { from: 14, to: 15, arrows: "to" },
    { from: 9, to: 26, arrows: "to" },
    { from: 26, to: 27, arrows: "to" },
    { from: 27, to: 28, arrows: "to" },
    { from: 28, to: 29, arrows: "to" },
    { from: 29, to: 30, arrows: "to" },
    { from: 28, to: 31, arrows: "to" },
    { from: 31, to: 32, arrows: "to" },
    { from: 32, to: 15, arrows: "to" },
    { from: 30, to: 15, arrows: "to" },
    { from: 1, to: 10, arrows: "to", hidden: true },
]);
